dist: xenial
sudo: required
language: python
python:
  - 3.5
  - 3.6
  - 3.7
  - 3.8
  - nightly
env:
  global:
    - BEANSTALKD_VERSION=1.11
install:
  - pip install -r requirements.txt
  - pip install codecov
  - wget https://github.com/beanstalkd/beanstalkd/archive/v${BEANSTALKD_VERSION}.tar.gz
  - tar -xzvf v${BEANSTALKD_VERSION}.tar.gz
  - pushd beanstalkd-${BEANSTALKD_VERSION} && make && sudo make install && popd
script: make test
after_success: codecov
